name: Build UnikAPI

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: echo "JAVA_8=$JAVA_HOME" >> $GITHUB_ENV
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: echo "JAVA_17=$JAVA_HOME" >> $GITHUB_ENV    
      - uses: actions/checkout@v2
      - name: Run Build Script
        run: | 
          chmod +x ${GITHUB_WORKSPACE}/build.sh
          ${GITHUB_WORKSPACE}/build.sh
        shell: bash
      - name: Upload Artifact To Workflow
        uses: actions/upload-artifact@v1
        with:
          name: UnikAPI
          path: ${GITHUB_WORKSPACE}/merge/UnikAPI.jar
          
