name: Sync Files with master Branch to laby4-unikapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest
    
    env:
      GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
      GIT_NAME: ${{ github.actor }}

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "${GIT_EMAIL}"
          git config --global user.name "${GIT_NAME}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Empty laby4-unikapi Branch
        run: |
          git checkout -B temp1
          git rm -r .
          git commit -m "Empty branch"
          git push origin temp1:laby4-unikapi --force
          
      - name: Copy Files to laby4-unikapi Branch
        run: |
          git checkout -B temp
          mkdir -p UnikAPI-Core/src/main/java/ml/volder/unikapi
          cp -R UnikAPI-Core/src/main/java/ml/volder/unikapi/* .
          git add .
          git commit -m "Copy files to laby4-unikapi branch"
          git push origin temp:laby4-unikapi --force
