name: Sync Files with master Branch to laby4-unikapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest
    
    env:
      GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
      GIT_NAME: ${{ github.actor }}

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "${GIT_EMAIL}"
          git config --global user.name "${GIT_NAME}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Empty laby4-unikapi Branch
        run: |
          git checkout -B temp
          git rm -r .
          git commit -m "Empty branch"
          git push origin temp:laby4-unikapi --force
          
      - name: Copy Files to laby4-unikapi Branch
        run: |
          git checkout master -- UnikAPI-Core/src/main/java/ml/volder/unikapi/*  # Copy files from master to temp
          git add UnikAPI-Core/src/main/java/ml/volder/unikapi/*   # Add copied files to staging area
          git commit -m "Copy files from master to temp branch"     # Commit changes
          git push origin temp:laby4-unikapi    # Push changes to remote temp branch

