name: Sync Files with master Branch to laby4-unikapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest
    
    env:
      GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
      GIT_NAME: ${{ github.actor }}

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "${GIT_EMAIL}"
          git config --global user.name "${GIT_NAME}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Empty laby4-unikapi Branch
        run: |
          git checkout -B temp
          git rm -r .
          git commit -m "Empty branch"
          git push origin temp:laby4-unikapi --force
          
      - name: Copy UnikAPI to laby4-unikapi Branch
        run: |
          git checkout master -- UnikAPI-Core/src/main/java/ml/volder/unikapi/*
          git checkout master -- UnikApi-Laby4/core/src/main/java/ml/volder/unikapi/*
          cp -a ./UnikApi-Laby4/core/src/main/java/ml/volder/unikapi/. ./UnikAPI-Core/src/main/java/ml/volder/unikapi/
          rm -r ./UnikApi-Laby4/
          git mv -f ./UnikAPI-Core/src/main/java/ml/volder/unikapi/* ./
          git add .
          git commit -m "Copy UnikAPI to laby4-unikapi Branch"
          git push origin temp:laby4-unikapi --force
        


