name: Sync Files with master Branch to laby4-unikapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest
    
    env:
      GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
      GIT_NAME: ${{ github.actor }}

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "${GIT_EMAIL}"
          git config --global user.name "${GIT_NAME}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Empty laby4-unikapi Branch
        run: |
          git checkout -B temp
          git rm -r .
          git commit -m "Empty branch"
          git push origin temp:laby4-unikapi --force
          
      - name: Copy UnikAPI-Core to laby4-unikapi Branch
        run: |
          git checkout master -- UnikAPI-Core/src/main/java/ml/volder/unikapi/*
          git checkout master -- UnikApi-Laby4/core/src/main/java/ml/volder/unikapi/*
          git mv UnikAPI-Core/src/main/java/ml/volder/unikapi/* ./UnikAPI-Core/
          git mv UnikApi-Laby4/core/src/main/java/ml/volder/unikapi/* ./UnikApi-Laby4/
          cp -a ./UnikAPI-Core/. ./UnikApi-Laby4/
          git add .
          git commit -m "Copy UnikAPI to laby4-unikapi Branch"
          git push origin temp:laby4-unikapi --force
          #git checkout --orphan temp2
          # git checkout master -- UnikAPI-Core/src/main/java/ml/volder/unikapi/*
          
          #shopt -s extglob  # Enable extended pattern matching
          # mv -f UnikAPI-Core/src/main/java/ml/volder/unikapi/* .
          #mv -f UnikApi-Laby4/core/src/main/java/ml/volder/unikapi/* .
          #git add .
          #git commit -m "Copy UnikAPI-Laby4 to laby4-unikapi Branch"
          #git rebase temp
          #git push origin temp2:laby4-unikapi


